<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PeTIK MUSTAHIK_loginform-captcha-image</name>
   <tag></tag>
   <elementGuidId>bc7b87ad-18dd-405a-9225-f3ffebf2cd52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='loginform-captcha-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginform-captcha-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>55d93880-e0c5-49c2-8dd1-fc25c25b08aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginform-captcha-image</value>
      <webElementGuid>447e527a-149a-4eb1-b646-6e3149ee96d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/backend/web/index.php?r=site%2Fcaptcha&amp;v=6606631d49fa36.67168862</value>
      <webElementGuid>2dad8f8a-9fda-4d70-a984-e31009a75708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform-captcha-image&quot;)</value>
      <webElementGuid>71c9ab30-4ea9-4a93-80da-49df7e0f3e2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='loginform-captcha-image']</value>
      <webElementGuid>56420856-6f5c-4e98-927f-ad5be859c3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[3]/img</value>
      <webElementGuid>4611885c-1257-4afc-90a1-0364685e193b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>491b33a1-f639-4a3f-88e8-57d1f055f84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'loginform-captcha-image' and @src = '/backend/web/index.php?r=site%2Fcaptcha&amp;v=6606631d49fa36.67168862']</value>
      <webElementGuid>3ac402d8-a2f5-46b1-a3ea-4bf22e4dfbb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
