<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PeTIK MUSTAHIK_password-button</name>
   <tag></tag>
   <elementGuidId>6bfee110-a088-4dac-ab99-46ced187b344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='password-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>205cd969-f5be-4419-9a03-a7731012e638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-button</value>
      <webElementGuid>4743744c-b979-40c4-a02b-85939d7cceb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-eye-slash</value>
      <webElementGuid>571b0ea3-e58e-4584-b65a-1c669ec4fcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-button&quot;)</value>
      <webElementGuid>b6362f1b-5bf3-4896-96e4-354e86a71e50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='password-button']</value>
      <webElementGuid>d914ee85-a94d-4bbf-af87-fe7b2ca72066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toggle-password']/span</value>
      <webElementGuid>f170eb53-3169-4c48-ba2b-3fd260cba5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>a2e1a40a-1369-4dd8-9034-c196e9a5595e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'password-button']</value>
      <webElementGuid>5a274fa3-419d-4965-b503-51b1d10eab7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
