<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PeTIK MUSTAHIK_password-button (1)</name>
   <tag></tag>
   <elementGuidId>6f4bc8ec-ba06-4404-9338-d7960914b57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='password-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>269045cf-f98e-4cab-9e47-9953092aaeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-button</value>
      <webElementGuid>46c97ddf-d1e5-4be9-8cad-02fdb116dcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-eye-slash</value>
      <webElementGuid>e7e55baf-e9ae-4be4-8309-8275ee7596e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-button&quot;)</value>
      <webElementGuid>4021f245-c84a-41f3-b35c-a43ca73e7fb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='password-button']</value>
      <webElementGuid>458cfe41-abff-4f1f-852a-ef221070f71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toggle-password']/span</value>
      <webElementGuid>bbeff5da-cb91-482b-826e-aff056766669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>dd8ab25c-d247-42c7-b678-3a3a4739a126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'password-button']</value>
      <webElementGuid>a068700d-2e68-4f3e-beef-03151d31da74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
