<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Lembar_jmlLembar (1)</name>
   <tag></tag>
   <elementGuidId>1b74984f-a78b-499f-88c8-ad7b7df45c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jmlLembar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jmlLembar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0ad5da4-263d-4d95-9694-d33d820a410c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8156d2ae-d13a-422c-847f-49bf5dfcb6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jmlLembar</value>
      <webElementGuid>f094a34c-70d2-4c15-9509-c668de968844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>jmlLembar</value>
      <webElementGuid>f97100c8-4816-42c7-9e28-63ddd65a2d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputtext-custom p-inputtext-xs p-inputnumber ng-untouched ng-pristine ng-valid p-filled</value>
      <webElementGuid>29bf6610-7749-474a-907f-5e1852febe5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jmlLembar&quot;)</value>
      <webElementGuid>dde55761-8eda-4848-805c-1f94abbda455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jmlLembar']</value>
      <webElementGuid>0a8ec852-944a-4ea3-9915-136785b14ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>2a6eecad-27f9-4968-a82c-40d72d5ac322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'jmlLembar']</value>
      <webElementGuid>77e0ef9f-f45d-4554-8d0c-fd0f50e0e70b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
