<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grup Dokumen_grpDokumen</name>
   <tag></tag>
   <elementGuidId>5330b763-2b8c-46a4-a6b3-a7919e5d90f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grpDokumen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='grpDokumen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f08b5b6-f824-4be5-adc4-3d28d7c9d5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grpDokumen</value>
      <webElementGuid>bb61e3f7-1b4b-4b1c-a0c7-400c5b17126e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>grpDokumen</value>
      <webElementGuid>2b9d10ac-cde2-4192-95e7-adb0611b7dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputtext-custom p-inputtext-xs p-inputtext-xlarge ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>a96bd75e-6018-4cb3-a57a-25dfb7119bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grpDokumen&quot;)</value>
      <webElementGuid>0b4719fd-0a1b-4fb9-9855-a2040b7fb681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='grpDokumen']</value>
      <webElementGuid>783c6eb8-673c-415c-9658-2004786c2de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9e4f674d-7b86-4268-992d-4585d0ba79e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'grpDokumen']</value>
      <webElementGuid>f80e9026-02ee-48e1-8164-d2d3c09f1401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
