<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jenis Dokumen_jenisDokumen</name>
   <tag></tag>
   <elementGuidId>7e1f2834-713c-48e0-bf57-757498b0d659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jenisDokumen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jenisDokumen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b78a81c-0b81-4d10-9e1e-3aec2d25a0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenisDokumen</value>
      <webElementGuid>f4f30e71-04d2-4306-9276-5f85d6dd2484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>jenisDokumen</value>
      <webElementGuid>1e123904-fcdb-41aa-824a-5eb2df219eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputtext-custom p-inputtext-xs p-inputtext-xlarge ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>49b86210-fb84-4c6c-96ba-f2077bd663a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenisDokumen&quot;)</value>
      <webElementGuid>15b0f105-81a7-45c6-9a8e-0b564f83f1da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jenisDokumen']</value>
      <webElementGuid>99f4972e-529b-4cc6-af55-2410bc94ab5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>15ac91de-bb93-40b3-919f-b9f9cf76dd21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jenisDokumen']</value>
      <webElementGuid>0f1ef672-0f0a-4c89-9571-f3c7f7179357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
