<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Item_noItem (1)</name>
   <tag></tag>
   <elementGuidId>5647c8aa-6129-4ea3-b6ff-d9886c172e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0851bff-dade-4f10-b0f7-1107bd1f2dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noItem</value>
      <webElementGuid>2be75510-f6e8-4a1f-a9b7-9c5857d2ab94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>noItem</value>
      <webElementGuid>7c3e1fb3-e7e1-4ac1-80a2-e85168e905a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputtext-custom p-inputtext-xs p-inputtext-xlarge ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b244f0ce-bc6d-4420-83ff-c081750fe61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noItem&quot;)</value>
      <webElementGuid>e3a03126-3f90-49a9-9e4b-c1d96bc3f841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noItem']</value>
      <webElementGuid>f5537899-c4e8-4e27-9436-128aa7a07856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>762cba3f-fd93-4623-a75a-e41743c9e038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'noItem']</value>
      <webElementGuid>b8435ef6-6440-47ad-b40d-2cd714652062</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
