<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Lembar_jmlLembar</name>
   <tag></tag>
   <elementGuidId>cdd5c154-9a34-43c7-9303-6de3686fe637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jmlLembar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jmlLembar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddd82b10-bf83-4cdc-8616-f644f3a14e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ba8cdaaa-f3c6-49c7-ab6c-27984a106192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jmlLembar</value>
      <webElementGuid>f084195c-c2d2-4b18-8e64-a9ff8cb60ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>jmlLembar</value>
      <webElementGuid>5a81c450-b194-4a38-892c-1cc37e1d57d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputtext-custom p-inputtext-xs p-inputnumber ng-untouched ng-pristine ng-valid p-filled</value>
      <webElementGuid>a87dc302-d758-47e9-88b2-780c41c53fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jmlLembar&quot;)</value>
      <webElementGuid>15ac102e-46b7-47d1-8a85-120a4f53f09f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jmlLembar']</value>
      <webElementGuid>d909e811-4364-420d-9b0d-8b25dbfd1759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>3449172d-497b-439c-9203-24ca217aaad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'jmlLembar']</value>
      <webElementGuid>2bc07a56-9c3d-4286-b6c6-cf0308c7b62b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
