<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Item_noItem</name>
   <tag></tag>
   <elementGuidId>ec71c732-7dfd-4417-acbf-554ba55872d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d858ce8-c8e7-4038-a710-745ae5769161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noItem</value>
      <webElementGuid>91191050-4404-4c28-88cb-c88df826171d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>noItem</value>
      <webElementGuid>c5b032ee-d748-45ae-894f-3c5b9d8c480d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputtext-custom p-inputtext-xs p-inputtext-xlarge ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>842da1b7-43ee-4ee6-8919-98ac98ac433d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noItem&quot;)</value>
      <webElementGuid>e7c2cf4c-e985-4bfd-9e3d-95973917d7be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noItem']</value>
      <webElementGuid>cb054df6-e5ec-49a9-891a-aa4604de65bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>def52f5e-c566-47fb-852d-e943910168db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'noItem']</value>
      <webElementGuid>f7365882-5fa4-47a8-a219-13d148cacf9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
