<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grup Dokumen_grpDokumen (1)</name>
   <tag></tag>
   <elementGuidId>b1502dd2-a855-48ba-b187-4e0262e36a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grpDokumen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='grpDokumen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aeec0273-0cc4-4197-8942-fcf1945db0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grpDokumen</value>
      <webElementGuid>bd4342f8-7cfe-4c00-a11e-ce815d49341a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>grpDokumen</value>
      <webElementGuid>9a2dbbc3-562d-4e02-9144-2ebf39c4004c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputtext-custom p-inputtext-xs p-inputtext-xlarge ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b9ad613b-5c74-4c89-8ce6-76e559b4c563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grpDokumen&quot;)</value>
      <webElementGuid>eb72d59b-a9a2-4d16-9f67-19a67a8d532d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='grpDokumen']</value>
      <webElementGuid>409f91cb-82cb-4524-99ca-e6ead7e5b387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5e27f966-b86a-4e47-9ca1-9e37bf700885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'grpDokumen']</value>
      <webElementGuid>028da99a-590b-4736-a790-47d8ec4eca57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
