<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jenis Dokumen_jenisDokumen (1)</name>
   <tag></tag>
   <elementGuidId>1c4c70de-7812-4e9a-9576-8a050f20e587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jenisDokumen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jenisDokumen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e948277-a8cf-4b1d-a052-cd1f8cb3a21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenisDokumen</value>
      <webElementGuid>dcf1bfce-17b2-45ef-b5f2-1a4a0d6f1d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>jenisDokumen</value>
      <webElementGuid>da3173fe-83b2-4baf-b6a9-1c9fbd10b89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputtext-custom p-inputtext-xs p-inputtext-xlarge ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>77397f11-9dc5-43ac-8a6f-4ae156b9bd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenisDokumen&quot;)</value>
      <webElementGuid>059b448c-3b33-4498-9ea9-f49acb2c9d4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jenisDokumen']</value>
      <webElementGuid>3d2ba57d-0eb5-4184-af9d-6d2df548cf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>0068f185-0c6b-4dbc-8130-3345fbb07bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jenisDokumen']</value>
      <webElementGuid>a23cfb7f-4639-4b6c-a5fe-ff5d1240565b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
